name: hypy
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  # scientific python
  - numpy
  - h5py
  - pandas
  # plotting
  - matplotlib
  - plotly
  # geospatial python
  - alphashape
  - gdal
  - geopandas
  - geojson
  - rasterstats
  - scikit-image
  - shapely  